/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;

public class Restaurant {
    protected String name;
    protected double stars;
    protected int priceCategory;
    protected List<Review> review = new ArrayList<Review>();

    public Restaurant(String name, int priceCategory) {
        this.name = name;
        this.stars = 0;
        this.priceCategory = priceCategory;
    }

    public String toString() {
        String output = this.name + " falls under a Price Category of " + this.priceCategory + " and has a review rating of " + this.stars + " stars. \n";
        int i = 0;
        while (i < this.review.size()) {
            output += "Review " + i + ": " + this.review.get(i).author + " rated it as " + this.stars + " and provided the following review: " + this.review.get(i).body + "\n";
            i++;
        }
        return output;
    }

    public void addReview(String body, String author, int stars) {
        this.review.add(new Review(body, author, stars));
//        int currentSize = this.review.size();
//        int currentReviewStars = this.review.get(currentSize-1).stars;
        calcRestaurantStars();
    }

    public void calcRestaurantStars(){
        int i = 0, sum = 0;
        while (i < this.review.size()) {
            sum += this.review.get(i).stars;
            i++;
        }
        this.stars = Math.round(sum/this.review.size());
    }

}
