/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

//import com.sun.xml.internal.bind.v2.runtime.output.StAXExStreamWriterOutput;
import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.Math;

public class RestaurantTest {

    Restaurant cheeseCakeFactory, redRobin, mcDonalds;

    @Test
    public void testRestaurant() {
        cheeseCakeFactory = new Restaurant("Cheesecake Factory", 3);
        redRobin = new Restaurant("Red Robin", 2);
        mcDonalds = new Restaurant("McDonald's", 1);

        //assertNull("Restaurant constructor should not return anything", classUnderTest);
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testAddReview() {
        testRestaurant();
        //cheeseCakeFactory = new Restaurant("Cheesecake Factory", 3);
        cheeseCakeFactory.addReview("I love this restaurant!", "Shan", 5);
        cheeseCakeFactory.addReview("It's ok!", "Bryan", 3);
        cheeseCakeFactory.addReview("I hate it", "Nick", 1);
        assertEquals((5+3+1)/3, cheeseCakeFactory.stars, 0);

        redRobin.addReview("I am fine with dining here if there's no other better option!", "Shan", 3);
        redRobin.addReview("It's ok!", "Nick", 2);
        redRobin.addReview("I am not that excited about this restaurant", "Bryan", 2);
        assertEquals(Math.round((3+2+2)/3), redRobin.stars, 0);

        mcDonalds.addReview("I love McDonalds!", "Nick", 4);
        mcDonalds.addReview("It's ok!", "Bryan", 3);
        mcDonalds.addReview("I hate it", "Shan", 1);
        assertEquals((4+3+1)/3, mcDonalds.stars, 0);
    }

    @Test
    public void testToString() {
        testRestaurant();
        testAddReview();

        String test = cheeseCakeFactory.toString();
        assertNotNull("Restaurant Class 'toString' method should return details about the restaurant", test);
        System.out.println(test);

        test = redRobin.toString();
        assertNotNull("Restaurant Class 'toString' method should return details about the restaurant", test);
        System.out.println(test);

        test = mcDonalds.toString();
        assertNotNull("Restaurant Class 'toString' method should return details about the restaurant", test);
        System.out.println(test);
    }


}
